### ISSUE TITLE
Request: Please allow monomorphic snps in the input 

### ISSUE THREAD

**Issue by holgerman** [molgenis/systemsgenetics#391]
Hi,

I am using magnificent Genotype Harmonizer 1.4.6 which is indeed very helpful!

I noticed, that Genotype Harmonizer allways filter out monomorphic SNPs from the input, even when 	specifying --mafFilter 0.0. It would be nice, if it filters maf larger than the given value, allowing maf of 0, i.e. monomorphic SNPs (may be by introcing an additional option [greater] vs. [greater or equal] for backwards compatibility)
A real-world usage-example would be when very many small datasets have to be harmonized in order to merge all of them in a single big dataset. Here, it would be expected, that some single datasets have appearently monomorphic SNPs.

Thanks and best,
Holger

**Comment by PatrickDeelen** [comment]
Dear Holger,

I'm happy to hear you like Genotype Harmonizer. 

You make a fair point. Normally you would indeed expect greater or equal behavior for MAF filters. I will have a look at this, although I'm a bit busy at the moment so it might take some time.

Regards Patrick

**Comment by PatrickDeelen** [comment]
Dear Holger,

We have made a new release of the Genotype Harmonizer here: https://github.com/molgenis/systemsgenetics/wiki/Genotype-Harmonizer-Download. This version should also solve your problem. It was not actually a problem with MAF filter but simply that the aliment part excluded these variants since it is not possible to calculate LD if the MAF is zero.

For non AT or GC variants this is not a problem so they are now included. The AT and GC cannot be aligned using LD so will be excluded unless you use --mafAlign of at least 0. 

Please let me know how it works out for you.

Regards Patrick
