### ISSUE TITLE
Possible error in how the ASEperRegion module tracks the dispersion estimates

### ISSUE THREAD

**Issue by arunkom** [molgenis/systemsgenetics#468]
Hi 
I find your ASE analysis software very useful for my work and comparatively easier to use than other available tools. However while looking into the dispersionFile.txt file, I found that the same entry (filename and dispersion estimate) is being repeated for all samples. Looking into the java code, I think the problem arises because the _**int i**_ defined in line 72 of the PhasedEntry.java file within cellTypeSpecificAlleleSpecificExpression folder is probably not being incremented. I believe this is not just a writing error and that the software is erroneously using this one value on tests for all samples. Could you please verify if that is the case. 

Also, in the ASE wiki page, please provide information on how to cite this software. 

Thanks
Arun

**Comment by adriaan-vd-graaf** [comment]
Hey Arun,

Thanks for using my program. Very nice to hear that you find it easy to use, it was one of the main goals for its creation. I'm very sad to hear that you find a problem with this bug.
I've made a commit and filed a pull request to fix it, that should be the end of it.

_Running it before the bug fix should still produce normal results, even with the bug. Only the dispersion file is wrong_ 

I've never encountered this bug because I've never had a use case for it. Hope this did not screw up to many of your analyses, but usually it will only result in weird results if you've used the dispersion file that was created from the buggy program in a second run. 

I usually first run ASEperSNP to make sure that the data I'm using is correct and then feed in the dispersion file from there into ASEperRegion. If using this workflow, your results were valid before the bugfix. 

Again, thanks for your interest in the program,
Adriaan

**Comment by arunkom** [comment]
Hi Adriaan, 
Your quick response is much appreciated and for now I'll follow your suggestion to feed the dispersion file created from ASEperSNP to the ASEperRegion run. 
But in the longer term, I'd like to keep the workflow simple and use only the ASEperRegion module. From what I understood, running the ASEperSNP module isn't really a prerequisite for performing the ASEperRegion test and that the ASEperRegion module when run without providing a dispersion file would calculate the dispersion values from the ASfiles and use those values for the beta binomial tests. So could you please provide the updated jar file following the bug fix. And please let me know the preferred way to cite your program.
Thank you very much
Arun

**Comment by arunkom** [comment]
Hi again,
I followed your suggestion to use ASEperSNP to generate the dispersion file, which it now correctly does. I supplied that dispersion file to run ASEperRegion. Surprisingly, the results were the same as in my earlier test run on ASEperRegion without supplying that file. Digging deeper into the java code, I believe the error in the dispersion file created during my earlier run using ASEperRegion module alone was indeed just a writing error and that the actual dispersion values taken for further tests are being correctly called through the BetaBinomOverdispInSample.java script. Please clarify if I got this right.
Thank you
Arun

**Comment by adriaan-vd-graaf** [comment]
Hey Arun,

You do have that right, only the dispersion file has incorrect results, the
rest of the analysis is still correct. Jar file is forthcoming, but the
pull request needs to be approved by someone else in the team, before it
will be built by our automated build system. If you need it yesterday, I
can send you a copy of the jar, otherwise it'll take a day orso as it is
currently evening in western Europe.

As for the publication to cite, the idea is that we want to integrate the
method into a bigger publication, but that is still far from finished. If
you are only interested in non-covariate specific effects, you could cite
the wasp paper: https://www.ncbi.nlm.nih.gov/m/pubmed/26366987/ as we share
the same methods for the association to ASE. And perhaps mention that you
use the software on our github page.

Hope this clears things up,
Adriaan

On Tue., 8 Nov. 2016 at 18:47, Arun Kommadath <notifications@github.com>
wrote:

Hi again,
I followed your suggestion to use ASEperSNP to generate the dispersion
file, which it now correctly does. I supplied that dispersion file to run
ASEperRegion. Surprisingly, the results were the same as in my earlier test
run on ASEperRegion without supplying that file. Digging deeper into the
java code, I believe the error in the dispersion file created during my
earlier run using ASEperRegion module alone was indeed just a writing error
and that the actual dispersion values taken for further tests are being
correctly called through the BetaBinomOverdispInSample.java script. Please
clarify if I got this right.
Thank you
Arun

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/molgenis/systemsgenetics/issues/468#issuecomment-259207391>,
or mute the thread

**Comment by arunkom** [comment]
Awesome. Yes, I'd prefer to have the jar file at your earliest convenience. Found your linkedin account and have messaged you there with my email id.
Thanks.
Arun

**Comment by adriaan-vd-graaf** [comment]
I've sent you an email, and will close when the pull request is merged.

Adriaan
